In [4]:
#step1:we have to import the dataset to the google colab
import pandas as pd #pd is an instance of pandas
df=pd.read_csv('Data.csv')#df is a variable,read_csv is a predefined function from pandas

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [7]:
#step2:grouping input columns and output columns
X=df.iloc[:,0:3]

In [8]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [9]:
Y=df.iloc[:,-1] #slicing the output column

In [10]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [11]:
X = X.values

In [12]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
Y=Y.values

In [15]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [16]:
#step-3:handling missing data
#scenario-1:missing values in numerical column
#calculate mean or average of that column
#scenario-2:missing values in non-numerical column
#Fill the empty value highly repeted in that column
#scenario-3:having missing values in huge dataset
#example:20000 dataset two rows have empty values out of 20000
#remove those empty values rows

import numpy as np
from sklearn.impute import SimpleImputer #

imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [17]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [18]:
from math import remainder
#step-4:handling the catagorial data
#which converts the extra data into numeric data.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')#encoder is a method which converts text to numeric
X=ct.fit_transform(X)


In [19]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [21]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [22]:
#step5:spilt the data into training and testing data
from sklearn.model_selection import train_test_split#train test split is a class which was imported from sk. model_selection #it is used to spliting the data into training and testing
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)


In [23]:
X_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0]], dtype=object)

In [24]:
X_test

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [25]:
Y_train

array([1, 1, 1, 0, 1, 0, 1, 0])

In [26]:
Y_test

array([0, 0])

In [27]:
#step6:feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [28]:
X_train

array([[0.0, 1.0, 0.0, 0.4075557568177074, 0.1003139022427917],
       [0.0, 0.0, 1.0, -1.6108156102795101, -1.6005307686200532],
       [1.0, 0.0, 0.0, -0.058222250973958195, 0.4476695040387244],
       [0.0, 1.0, 0.0, -1.1450376024878446, -0.9537306825172813],
       [1.0, 0.0, 0.0, -0.3687409228350686, -0.5225306251154334],
       [1.0, 0.0, 0.0, 1.0285931005399283, 0.9866695757910343],
       [1.0, 0.0, 0.0, 1.649630444262149, 1.741269676244268],
       [0.0, 0.0, 1.0, 0.09703708495659699, -0.19913058206404746]],
      dtype=object)

In [29]:
X_test

array([[0.0, 0.0, 1.0, 0.21779434623591784, -1.1693307112182052],
       [0.0, 1.0, 0.0, 1.9601491161232594, 2.172469733646116]],
      dtype=object)

In [30]:
#machine learning
#1.supervisioned learning-when we have labeled data,and the model tasks are classification or prediction
#a.linear regression
#b.logistic regression
#2.un-supervisioned learning-unlabeled data,model remembers the patterns,we can perform prediction also.
#3.reinforcement learning-model will learn from failures(trail and error method)

In [31]:
#logistic regression algorithm-when model perform a classification task we have to apply logistic regression alogorithm
#linear regression algorithm-when model performs prediction task we have to apply linear regression algorithm

In [32]:
#step7:apply algorithm to the dataset
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression()

In [33]:
Y_pred=classifier.predict(X_test)

In [34]:
Y_pred

array([1, 1])